### ISSUE TITLE
[waiting review} mic encapsulate wrapper fails

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#168]
I created a component with an input and an output (manually). When I executed `mic encapsulate wrapper` MIC fails:
```
mic encapsulate wrapper
Traceback (most recent call last):
  File "/usr/local/bin/mic", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mic/click_encapsulate/commands.py", line 321, in wrapper
    render_io_sh(mic_directory_path, inputs, parameters, configs)
  File "/usr/local/lib/python3.6/dist-packages/mic/component/initialization.py", line 112, in render_io_sh
    list_config = [value[PATH_KEY] for key, value in configs.items()]
AttributeError: 'list' object has no attribute 'items'
```

**Comment by sirspock** [comment]
Fixed

**Comment by dgarijo** [comment]
I still experience this issue after updating mic inside the image with `pip install git+https://github.com/mintproject/mic.git@develop -U`

**Comment by dgarijo** [comment]
Files used for test attached
[mic_test_python.zip](https://github.com/mintproject/mic/files/4796103/mic_test_python.zip)

**Comment by dgarijo** [comment]
What am I being assigned here?

**Comment by sirspock** [comment]
I was waiting for your review but the unit test is enough.
